Resources:
  UserPoolLambdaInvokePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:invokeFunction'
      Principal: 'cognito-idp.amazonaws.com'
      FunctionName: ${self:service}-${self:provider.stage}-createProfile
      SourceArn:
        Fn::GetAtt:
          - UserPool
          - Arn