Resources:
  ProfilesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: HC-${self:provider.stage}-ProfilesTable
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
        - AttributeName: 'email'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'id'
          KeyType: 'HASH'
      GlobalSecondaryIndexes:
        - IndexName: 'gsi_email'
          KeySchema:
            - AttributeName: 'email'
              KeyType: 'HASH'
          Projection:
            ProjectionType: 'ALL'
      BillingMode: 'PAY_PER_REQUEST'